#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

while [[ $# > 0 ]]; do
	if [[ $1 == "--dry" ]]; then
		dry="1"
	fi
	shift
done

log() {
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "➜ $@"
	fi
}

execute() {
	if [[ $dry == "1" ]]; then
		log "would execute: $@"
		return
	fi
	"$@"
}

success() {
	log "✓ $@"
}

log "--------- Updating Neovim Configuration ---------"

NVIM_REPO="git@github.com:nezudevv/nvim_basic.git"
NVIM_DIR="$HOME/.config/nvim"

if [ -d "$NVIM_DIR/.git" ]; then
	log "Neovim config exists, pulling latest..."
	execute git -C "$NVIM_DIR" pull
	success "Neovim config updated"
else
	log "Cloning neovim config..."
	execute rm -rf "$NVIM_DIR"
	execute git clone "$NVIM_REPO" "$NVIM_DIR"
	success "Neovim config cloned"
fi

log ""
success "Neovim configuration is up to date!"
